### ISSUE TITLE
Incorrect key generated when using composite operation on patch/update

### ISSUE THREAD

**Issue by JosephSuyam** [tywalch/electrodb#372]
**Describe the bug**
Incorrect key is generated for `pk` and `sk` when adding **.composite** on patch/update. I've also added the 2 scenarios on the [playground link](https://electrodb.fun/?ssl=111&ssc=42&pln=111&pc=48#code/PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2AT0IBlTADcsAY1IBfbhiiSwAckRwjVSzABGNgNzijUPrgVUGFwRSAF5bBkcsfTgAfQZpaQRjBg0fXA8vNIUABSg-ABVNaVClUTAwbIAlAHkAKRUAYXyALltsywArByobfDKwBpVK-IBJADERhoBBfJVWmwbMDS5kqjhe-oAhABlqgHF5zYQoAHMN009Rb18cvKodAKpUITDFfqmmkYA1OdsP0Z+G3K2RUADkACIjUEHNpgyHQoFgAASI3B4LB8xRaLBiJUAA1sttJiMWrZ8YTiflEVD-t9fjYaZ9AX0LuJQGB8gxcABrIRqDRUTTCMTXPwVO4vMB8OAsVTqLQACn6b3K5UksEQrRVqvK-AFmnmsj86T6OvK0QwuCwPnmAEZETriBhDCZ5kZJCb+uVTKbVSknFgXKg1rgtV7Vc9MCMYGGzarBcV5n5sHwzr64+Q0FhyDGwE50OmzcBgGB4FwGJQqK0FQBKMAhAB8YFQqCwMFrhe9nbzRTgsbjPcTYGqLi6jgAdPoGAh0LgFbkCr2a93ypnWznWvm4N2feHygLgv24wm+7Zk1hUw6zWvs3Bc1ud934LgjNhpKk+EezSekwHLyuyDgLMNzzDACz3MBdzjf0IjoSQ9VDUoB0HU8bHPf8IKg784BkBAUlPbVj17X8UzTTDuz8FJni-HUf2HUduknadZ3nO4Hio3Blwg8oywrahWgXe5HmecdaR+ACbxAh9yIguAAA9pFvKYqyQgc6JsPhUEkFxMCvHUWBSIw6FaABtNDhPSABdCS4AYGBqj4BADVA8C4ywrtwwveA5LwGiwCNFTCLNbwEGCSIbVsALtiwPw9NVaRuT8nVvBkPJ2FPMzIwwaMbGs7jVRWRBcxsBK4o85CeSS1UUqNdLTJsE9elsA91jy5DykKhBip5MrIMfCCWqqrz5PmE4rVtBKAFoxqwW0eUm4a5N6hKqo6nAutG8bSoA8oarStZ6pa3KAPcs1KtU5DOuKma5u5XrdqsWqDrATKnRytqB1O8rVSwrDlACIIzD6GtLlFBQsujetbAAVgATgADi4AAGAAmW0ABZJoAZltW0Ucm9GGEJyaXCxnTJoAdgYLgKfR204GhmAjAxjIwZQqGbCOU5WayPN2GCDnUGkGB8JgHmbn8u4oaC9TpVlRrC0G2w5b5qhgivZ9Xywd9rU-ZWZVLPAjCvSinkQjSDdN54rxgoz4PUc2VdtuCEKvNZcPw+YVfdxJ8POS5izASosBOOgFCnGc8DAIMFBYSxUzAbk4E0URBNwcdpEMugFWUCGYEIOiAvHE8C-508i5PSCa36cdiCoHPw01t8P1aIum+1j9C2d+2aFbu4AH5x27hDFZw33noCwefbwtZfVMavykDvgoAUXBUGYLAuDALAwCMBg+DAOyYHZuhMFIGPALX6ht6EDhSFwBh4JrvarTWHPmze-OUNLtWzAXsBxwnCgLWAOJYADq8cThgAjrOaOwZd5yHII4ROydU4Sgzlnd+ecC69h-gLeeNc64Nx1O3HWEU25G2brrLuVAAh2wQn3Pwg9h4O1Hh7CeA9i5jxntufoBDF4lmXqvdepBN7b13vvQ+MBj6FzuMXXsYBT7MAvuQK+CgYp5lPkQR+cBn6PX2nALBn8cFDgrrg1Wh5JZ+HkcUKuNcgEgNEEAA).

**ElectroDB Version**
2.13.1

**ElectroDB Playground Link**
[ElectroDB Playground](https://electrodb.fun/?ssl=111&ssc=42&pln=111&pc=48#code/PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2AT0IBlTADcsAY1IBfbhiiSwAckRwjVSzABGNgNzijUPrgVUGFwRSAF5bBkcsfTgAfQZpaQRjBg0fXA8vNIUABSg-ABVNaVClUTAwbIAlAHkAKRUAYXyALltsywArByobfDKwBpVK-IBJADERhoBBfJVWmwbMDS5kqjhe-oAhABlqgHF5zYQoAHMN009Rb18cvKodAKpUITDFfqmmkYA1OdsP0Z+G3K2RUADkACIjUEHNpgyHQoFgAASI3B4LB8xRaLBiJUAA1sttJiMWrZ8YTiflEVD-t9fjYaZ9AX0LuJQGB8gxcABrIRqDRUTTCMTXPwVO4vMB8OAsVTqLQACn6b3K5UksEQrRVqvK-AFmnmsj86T6OvK0QwuCwPnmAEZETriBhDCZ5kZJCb+uVTKbVSknFgXKg1rgtV7Vc9MCMYGGzarBcV5n5sHwzr64+Q0FhyDGwE50OmzcBgGB4FwGJQqK0FQBKMAhAB8YFQqCwMFrhe9nbzRTgsbjPcTYGqLi6jgAdPoGAh0LgFbkCr2a93ypnWznWvm4N2feHygLgv24wm+7Zk1hUw6zWvs3Bc1ud934LgjNhpKk+EezSekwHLyuyDgLMNzzDACz3MBdzjf0IjoSQ9VDUoB0HU8bHPf8IKg784BkBAUlPbVj17X8UzTTDuz8FJni-HUf2HUduknadZ3nO4Hio3Blwg8oywrahWgXe5HmecdaR+ACbxAh9yIguAAA9pFvKYqyQgc6JsPhUEkFxMCvHUWBSIw6FaABtNDhPSABdCS4AYGBqj4BADVA8C4ywrtwwveA5LwGiwCNFTCLNbwEGCSIbVsALtiwPw9NVaRuT8nVvBkPJ2FPMzIwwaMbGs7jVRWRBcxsBK4o85CeSS1UUqNdLTJsE9elsA91jy5DykKhBip5MrIMfCCWqqrz5PmE4rVtBKAFoxqwW0eUm4a5N6hKqo6nAutG8bSoA8oarStZ6pa3KAPcs1KtU5DOuKma5u5XrdqsWqDrATKnRytqB1O8rVSwrDlACIIzD6GtLlFBQsujetbAAVgATgADi4AAGAAmW0ABZJoAZltW0Ucm9GGEJyaXCxnTJoAdgYLgKfR204GhmAjAxjIwZQqGbCOU5WayPN2GCDnUGkGB8JgHmbn8u4oaC9TpVlRrC0G2w5b5qhgivZ9Xywd9rU-ZWZVLPAjCvSinkQjSDdN54rxgoz4PUc2VdtuCEKvNZcPw+YVfdxJ8POS5izASosBOOgFCnGc8DAIMFBYSxUzAbk4E0URBNwcdpEMugFWUCGYEIOiAvHE8C-508i5PSCa36cdiCoHPw01t8P1aIum+1j9C2d+2aFbu4AH5x27hDFZw33noCwefbwtZfVMavykDvgoAUXBUGYLAuDALAwCMBg+DAOyYHZuhMFIGPALX6ht6EDhSFwBh4JrvarTWHPmze-OUNLtWzAXsBxwnCgLWAOJYADq8cThgAjrOaOwZd5yHII4ROydU4Sgzlnd+ecC69h-gLeeNc64Nx1O3HWEU25G2brrLuVAAh2wQn3Pwg9h4O1Hh7CeA9i5jxntufoBDF4lmXqvdepBN7b13vvQ+MBj6FzuMXXsYBT7MAvuQK+CgYp5lPkQR+cBn6PX2nALBn8cFDgrrg1Wh5JZ+HkcUKuNcgEgNEEAA)

**Entity/Service Definitions**
Include your entity model (or a model that sufficiently recreates your issue) to help troubleshoot.

```
{
    model: {
      entity: 'posts',
      version: '1',
      service: 'cms',
    },
    attributes: {
      userId: {
        type: 'string',
        required: true,
        // default: () => uuid(),
      },
      type: {
        type: Object.values(PostType),
        required: true,
      },
      title: {
        type: 'string',
        required: true,
      },
      description: {
        type: 'string',
        required: true,
      },
      attachments: {
        type: 'string',
      },
      template: {
        type: 'string',
      },
      status: {
        type: Object.values(PostStatus),
        default: PostStatus.ACTIVE,
        required: true,
      },
      createdAt: {
        type: 'string',
        default: () => date_time,
        readOnly: true,
      },
      updatedAt: {
        type: 'string',
        watch: '*',
        set: () => date_time,
        readOnly: true,
      },
      expireAt: {
        type: 'number',
        watch: ['status'],
        set: (_, { status }) => {
          if (status === PostStatus.INACTIVE) getUnixTime(addDays(new Date(), 30));
        },
        readOnly: true,
      },
    },
    indexes: {
      post: {
        collection: 'postList',
        pk: {
          composite: ['userId'],
          field: 'pk',
        },
        sk: {
          composite: ['type', 'title'],
          field: 'sk',
        },
      },
      title: {
        index: 'gsi1pk-gsi1sk-index',
        pk: {
          field: 'gsi1pk',
          composite: ['title'],
        },
        sk: {
          field: 'gsi1sk',
          composite: ['userId'],
        },
      },
    },
  }
```

**Expected behavior**
To be able to update the values of composite keys -- `title` and `type` for my model.

**Errors**

```
{
  _message: undefined,
  message: 'Error thrown by DynamoDB client: "The conditional request failed" - For more detail on this error reference: https://electrodb.dev/en/reference/errors/#aws-error',
  name: 'ElectroError',
  ref: {
    code: 4001,
    section: 'aws-error',
    name: 'AWSError',
    sym: Symbol(error-code)
  },
  code: 4001,
  date: 1712645861976,
  isElectroError: true
}
```

**Additional context**
Not sure if there is just missing on my usage on composite key.

**Comment by tywalch** [comment]
Hi @JosephSuyam 👋 

I took a look at your example and I [created a playground](https://electrodb.fun/?#code/PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2AT0IBlTADcsAY1IBfbhiiSwAckRwjVSzABGNgNzijUPrgVUGFwRSAF5bBkcsfTgAfQZpaQRjBg0fXA8vNIUABSg-ABVNaVClUTAwbIAlAHkAKRUAYXyALltsywArByobfDKwBpVK-IBJADERhoBBfJVWmwbMDS5kqjhe-oAhABlqgHF5zYQoAHMN009Rb18cvKodAKpUITDFfqmmkYA1OdsP0Z+G3K2RUADkACIjUEHNpgyHQoFgAASI3B4LB8xRaLBiJUAA1sttJiMWrZ8YTiflEVD-t9fjYaZ9AX0LuJQGB8gxcABrIRqDRUTTCMTXPwVO4vMB8OAsVTqLQACn6b3K5UksEQrRVqvK-AFmnmsj86T6OvK0QwuCwPnmAEZETriBhDCZ5kZJCb+uVTKbVSknFgXKg1rgtV7Vc9MCMYGGzarBcV5n5sHwzr64+Q0FhyDGwE50OmzcBgGB4FwGJQqK0FQBKMAhAB8YFQqCwMFrhe9nbzRTgsbjPcTYGqLi6jgAdPoGAh0LgFbkCr2a93ypnWznWvm4N2feHygLgv24wm+7Zk1hUw6zWvs3Bc1ud934LgjNhpKk+EezSekwHLyuyDgLMNzzDACz3MBdzjf0IjoSQ9VDUoB0HU8bHPf8IKg784BkBAUlPbVj17X8UzTTDuz8FJni-HUf2HUduknadZ3nO4Hio3Blwg8oywrahWgXe5HmecdaR+ACbxAh9yIguAAA9pFvKYqyQgc6JsPhUEkFxMCvHUWBSIw6FaABtNDhPSABdCS4AYGBqj4BADVA8C4ywrtwwveA5LwGiwCNFTCLNbwEGCSIbVsALtiwPw9NVaRuT8nVvBkPJ2FPMzIwwaMbGs7jVRWRBcxsBK4o85CeSS1UUqNdLTJsE9elsA91jy5DykKhBip5MrIMfCCWqqrz5PmE4rVtBKAFoxqwW0eUm4a5N6hKqo6nAutG8bSoA8oarStZ6pa3KAPcs1KtU5DOuKma5u5XrdqsWqDrATKnRytqB1O8rVSwrDlACIIzD6GtLlFBQsujetbAAVgATgADi4AAGAAmW0ABZJoAZltW0Ucm9GGEJyaXCxnTJoAdgYLgKfR204GhmAjAxjIwZQqGbCOU5WayPN2GCDnUGkGB8JgHmbn8u4oaC9TpVlRrC0G2w5b5qhgivZ9Xywd9rU-ZWZVLPAjCvSinkQjSDdN54rxgoz4PUc2VdtuCEKvNZcPw+YVfdxJ8POS5i2bYg8zoUgpxnPALCsMAAAMApj0RBNwcdpEMugFWUCGYEIOiAvHE8c-50885PSCa36cdiCoDPw01t8P1aPO6+1j9C2d+2aEbu4AH5x3bhDFZw33noC3ufbwtZfVMcvykD-JQ9jvarTWWsY7AeCOFgMAYrAHwnJQmBuDkMAl-SsB-WwIMQzAUFqnyfzyGIdRt74EPSEkBgLzAfpA4BgXFvHByOgO8d46SMBWYOm9g7h1nOfZg4C+B8CgAoIyDBUzbnXgwbkF4Thv2sFISQwZAjBEAfPUgP8SwxxPGvC+gZgykB3kghQ0hH56jAKHZgYCIEMIUDvFheA2Ffw4O-T+r8-4MIEPJUhocKFgBgZHFhUBDDwEPlQKAi9Hr7TgKvdezwFAfyoEZN+cjmKRz8HIO8u8xELw0PBHOHC4BcAsS-WRHAd7gOIIQRRyicGliwFwLgmA2HyKEBwNBrBGAKCYKQbxbZLFqOMXHNOa8N50C3mwUKsjwGRnPifHwMB2C6xPqHIw3IwCYEsBgQBFdT4r0zm9bOqtDySz8PnXsZcK4nCgLWAOJZhHlEThKFOacM5ByjI0guTSzAzzAJXOA1cgrNx1hFJuRt666zblQAIdsEJdz8L3fuDtB4exHj3fOQ8J7bn6NPWRZCNGpWXtomsKT5lpMPjvPeQoTyHycRgPJDyz60KvpHW+99+FP14dYkRX9XHEIkd5aRIChBcJyVAsOpihDRJPmgphxS0EnAwR-bBqY8Hb0kIQ8R0jyGz0odQ8+WzL70O3kIXF4K2EOLACi4O7BmUPwEc-IRC8P5CLhS-BFQC4CyJCQ-JRcTVHqJjrUp5KS9GYMMZwfp0rzE5iscY2xGDhHkF+RI1xwChAeIwbEgpJKCkBKCc-aVYTX4sEiXAmJlhlHxPUf0pJ6qXmb0PhkhAWTuG5OuAUj8xSHBlIqXIap5RxxKtGVnQuatpmdO6SDUQQA) to help explain it a bit, but I also do that here.

The `composite()` method exists to help provide additional context to an `update` or `patch` to ensure indexes can be built completely. For example, if you `set` a single attribute that is involved in a >1 composite index ElectroDB will recognize this action will cause inconsistencies between the index key and the individual attributes and throw. ElectroDB treats consistency between a composite index and it's individual attribute values as critical, and limitations with DynamoDB require these values all provided at the same time.

Going back to `composite()` this is present because some values in a composite can be readOnly, so they cannot be provided via `set`. This method allows you `set` the mutable parts of an index and provided readOnly parts to keep your indexes consistent with the underlying values. 

In the example you provided, unfortunately there is a logical issue. The `post` index (your main table index) is defined with the composite attributes `userId`, `type`, and `title`. Because these attributes together form the primary key of your item, they become `readOnly` by default. In both of your examples, the values for those attributes differ between what is passed to the `patch` method and what is passed the the `composite` method.

```typescript
// `patch()` gets the values from `post`
Posts.patch({ userId, type: post.type, title: post.type })
  .set({
    description: post.description,
    attachments: post?.attachments,
    template: post?.template,
  })
// `composite()` gets different values
  .composite({ userId, type, title })
  .go();
```

```typescript
// `patch()` gets the top level values
Posts.patch({ userId, type, title })
  .set({
    description: post.description,
    attachments: post?.attachments,
    template: post?.template,
  })
  // `composite()` gets the values from `post`
  .composite({ userId, type: post.type, title: post.type })
  .go();
```

The issue here is that this would result your `title` index (`gsi1pk-gsi1sk-index`) having different values than your attribute and main table index.

ElectroDB relies on the addition of this Conditional Expression to ensure that values provided via `composite` are truely the values on the attribute: `"(attribute_exists(#pk) AND attribute_exists(#sk) AND #userId = :userId0) AND #title = :title0"`. In your cause they wouldn't so both will throw the exact error you provided.

I hope this helps, please let me know if I can clarify further in any way! I appreciate you creating the issue, it helps me understand the areas of the library the can use more clarification, attention, and documentation!

**Comment by JosephSuyam** [comment]
Hi @tywalch, so basically composite keys are immutable and `composite()` is pretty much a 'where()' for composite keys right?

I initially thought that `composite()` would enable the update on the composite keys. Thanks for clarifying, I'll close this issue now. Ohh and can you confirm if this is correct.

> so basically composite keys are immutable and `composite()` is pretty much a 'where()' for composite keys right?

**Comment by tywalch** [comment]
Yes, I'd say you pretty much got it 👍 

When the attributes being `set` on an `update()` call would only provide ElectroDB with enough data to make a partial key, ElectroDB throws to prevent consistency issues. The `composite()` method is helpful when you can't use `set` on a composite attribute because it's `readOnly`, but without it ElectroDB would throw because it is missing. Additionally, to further enforce consistency, ElectroDB also adds `where` conditions on the attributes passed to `composite()`.
