### ISSUE TITLE
Doc example incorrect and misleading

### ISSUE THREAD

**Issue by iOSonntag** [tywalch/electrodb#374]
Hey folks, GREAT JOB on ElectroDB absolutely dope what you have build!!

Just a quick note on one doc example I found to be misleading. In the ConditionExpression section under examples [here](https://electrodb.dev/en/mutations/conditions/#examples) in the "dynamic" filtering example is a logical issue (I think).

As I understood the framework, chained where clauses lead to implicit `AND`s and if thats the case then the example will never ever return any item.  That is because it tries to find an item where the `keeper` attribute is two different values at the same time (pratically impossible).

My suggestion would be to update the example to use `OR` instead, but I am not sure how to do this in order for the example to still contain that for loop. That is why I have not edited the page.

**Comment by tywalch** [comment]
Great catch! I usually accept and merge pretty much any documentation PRs; I'm not very opinionated about how an inaccurate example would be changed, so if you wanted to remove the loop entirely (for example) I'd be totally fine with that. If you'd like to make a PR I'd stamp it, otherwise I'll note this for my next documentation commit!

**Comment by iOSonntag** [comment]
@tywalch  Alright I just reversed the condition to not equal `ne()` that should do the trick I guess. Pull request #379

**Comment by iOSonntag** [comment]
Closed merge of #379
