### ISSUE TITLE
Collection validation should check `field` property of composite attributes

### ISSUE THREAD

**Issue by raryanpur** [tywalch/electrodb#394]
**Describe the bug**
When defining a collection, ElectroDB validates composite attributes without checking the `field` property. Since collections map to DynamoDB queries, and composite key attributes are mapped to DynamoDB names using the `field` property if it's specified, the collection validator should take this property into account.

**ElectroDB Version**
`2.14.1`

**ElectroDB Playground Link**
N/A

**Entity/Service Definitions**
Include your entity model (or a model that sufficiently recreates your issue) to help troubleshoot.

```
{
    model: {
        entity: "restaurant",
        service: "app",
        version: "1"
    },
    attributes: {
        id: {
            type: "string"
            field: "restaurantId"
        },
        name: {
            type: "string"
        }
    },
    indexes: {
        record: {
            collection: "patrons"
            pk: {
                field: "pk",
                composite: ["id"],
            },
            sk: {
                field: "sk",
                composite: ["name"],
            },
        }
    }
}
{
    model: {
        entity: "customer",
        service: "app",
        version: "1"
    },
    attributes: {
        restaurantId: {
            type: "string"
        },
        name: {
            type: "string"
        }
    },
    indexes: {
        record: {
            collection: "patrons"
            pk: {
                field: "pk",
                composite: ["restaurantId"],
            },
            sk: {
                field: "sk",
                composite: ["name"],
            },
        }
    }
}
```

**Expected behavior**
The collections schema validator should check the `field` property during schema validation and the above should succeed.

**Errors**

```
ref: {
      code: 1013,
      section: 'join',
      name: 'InvalidJoin',
      sym: Symbol(error-code)
},

```

**Comment by tywalch** [comment]
Hi @raryanpur 👋 

Thanks for submitting this! Ultimately the reason this validation exists on the attribute name (as opposed to the field) is because the attribute _name_ is what's used when performing a collection query. The validation prevents ambiguity around which attributes must be provided to perform the query, and keeps the api simple. For example, if the entities you included were not validated this way, which query would be correct?

```typescript
service.collections.patrons({ restaurantId: 'wendys' }).go();  
```

```typescript
service.collections.patrons({ id: 'wendys' }).go();  
```

```typescript
service.collections.patrons({ id: 'wendys', restaurantId: 'wendys' }).go();  
```

Going a step further, if the "customer" entity was defined with an `id` field as well (which I think would be likely with this pattern, then `id` it gains additional ambiguity:

```typescript
{
    model: {
        entity: "customer",
        service: "app",
        version: "1"
    },
    attributes: {
        id: {
            type: "string"
        },
        restaurantId: {
            type: "string"
        },
        name: {
            type: "string"
        }
    },
    indexes: {
        record: {
            collection: "patrons"
            pk: {
                field: "pk",
                composite: ["restaurantId"],
            },
            sk: {
                field: "sk",
                composite: ["id"],
            },
        }
    }
}
```

These are just a few examples to illustrate why the library optimizes a bit more for simplicity here. The typing system also benefits from this approach, which is a top priority for the library. Definitely share any thoughts you have about the above however, the more brains on this topic the better because it has come up before!

**Comment by raryanpur** [comment]
Thanks for the info! Need some time to digest but makes sense on first pass.

**Comment by raryanpur** [comment]
Much delayed response, but after working with Electro more definitely understand why overloading keys isn't a good design choice. Closing as not planned.
