### ISSUE TITLE
Conditional `where` operations

### ISSUE THREAD

**Issue by raryanpur** [tywalch/electrodb#443]
Thanks again for building and supporting ElectroDB - it's awesome!

Is there a supported way to write conditional where operations? Currently, I just have the where operation return an empty string if the filter expression shouldn't be applied.  e.g.

```
    const { data } = await entity.query
      .byIndex({ entityId: id })
      .where((attr, { eq }) =>
        someValue == null
          ? ""
          : eq(attr.someValue, someValue),
      )
      .go()
```

This works in practice (and is particularly helpful when using Electro to query in response to a `GET` request with optional query string parameters [e.g. `my.rest.api/entity/<id>?someValue=x`]), and the source for `where` looks like this is explicitly supported and not unhandled behavior, but wanted to confirm to be sure.

**Comment by tywalch** [comment]
Thanks @raryanpur 👋 

You are correct that this fully supported behavior! The cool thing about using `where` is that the string returned from that query is _actually_ the string that gets used in the `FilterExpression`. This is intentional so folks can have even more control over how their filter expressions are written. You could even do something like this:

```typescript
 const { data } = await entity.query
      .byIndex({ entityId: id })
      .where((a, { value }) =>
        someValue == null
          ? ""
          : `somevalue = ${value(a.someValue, someValue)}`,
      )
      .go()
```

**Comment by raryanpur** [comment]
Great, thanks @tywalch !
