### ISSUE TITLE
Attribute Watching: subtract() results in not passing the new value to the setter

### ISSUE THREAD

**Issue by julian99m** [tywalch/electrodb#453]
**Describe the bug**
When calling the subtract() method on a watched attribute, the setter of the watching attribute will not be called with the new value, but rather with the value that was subtracted from the original value. 
Example: original value is 5, subtract method is called with parameter 2, the setter will not be called with 3 (new value), but with 2 (parameter of the subtract-call).

**ElectroDB Version**
3.0.1

**ElectroDB Playground Link**
[ElectroDB Playground](https://electrodb.fun/?#code/PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2ATzABfbhiiSwAIkRwAxlQMwARsYDc481D64FVBjYSkAvCc1QqBgA+h5ecMF8DJJwDuKgYACqxBhCahpU2iKizq4KqClCfnxwLKrqWgAUomBKNbVgkrCIAFx1DQ38GZptxgWYxvj1HSkAbljmcL0euADWDNLSg8MNo5i4WC69AIzGKzpDHQxUVlg2qFR4bYortf0Y17cNmdJTJm7YfADmex21B09nKh1JhHn9nppXr0+KhJDYBk8AeCgSCMAARVDSBATY5vG7g2ovN7GGFwgaHAnkBgwADyfAQPTAVnQFPBLGO5jobQA2gByFGXDC8gC6rL+xCobUqwUIigFmB0AEowD4AHxgeUYRH7MVYARwAAeV3afxiZNSYIJzgQ3ksmz4vTkXwYfCwAC9jvblgSwNJZpafc4ZFANpceX0UsZRU8OlwcAgYL0-b8CUiCXMA1bDLJQ29uRGBtGfbU44hE+9ZinwTptR0a-8Kcowt5dKJFY4ci43GB7iqTPcALS7DvAYBgACSro0DCQoxn6DaAFZRPdcAA6cxUy6VRT3QiapdKtdfKCVRXxMcAZVQNisDEsYAATPpDGBl6u19IOXQd-cj7gbzvSwdwPJ8jxPM8L1ybtyAA6g+wYdl2B7QpjzgKhfxScDT3PUdoKgbw1wQKAvkqAADABhQJUTaAASRRYMoKg1xgY4GAAfg3ajBQOMAKJnBAbHvf0wHoxjqBYtjOM1DEsRxS4dDIxUgA)
(The behavior can be observed in the resulting update operation)

**Entity/Service Definitions**
see Playground

**Expected behavior**
Without further explanation in the docs, I would expect the _new_ value (3) to be passed to the setter. 
If the observed behavior is correct, it should be explicitly mentioned in the docs. But as the operation is not given in the setter callback, the provided value can not be interpreted and thus holds no valuable information, so I think the behavior should be changed, if possible.

**Comment by tywalch** [comment]
Hey @julian99m 👋 

Great question, this could definitely use more explanation on the docs! 

> Without further explanation in the docs, I would expect the new value (3) to be passed to the setter.

This is fair to assume, though unfortunately not possible with a single request to DynamoDB. The setter is called prior to your mutation request to DynamoDB, so ElectroDB won't have access to the result of the subtraction (or addition) operation.

> But as the operation is not given in the setter callback

I was actually surprised to see the `counter` value in the second argument, I had only expected that value to be there if it was called with a `set` operation. Let me do some research into how that is implemented. My assumption is wrong, the solve may be to add the operation (`set`, `add`, `subtract`, etc) as a third argument so that fix is simply to roll forward. 

Let me know if this raises any additional questions you have in the meantime 👍

**Comment by tywalch** [comment]
I looked into the scope of work it would take to add operation context to the values passed to `set`; unfortunately, it is a lot. It has been a while since I dug into that area of the library, but it appears to supply all values associated with the mutation consistently (bittersweet).

To address the titular concern, I want to reiterate that any value passed to an attribute setter is a value that was `provided` to the operation, not the values stored in the database. To do this, a write-after-read operation would be necessary, which is also not the type of operation ElectroDB would perform because it is unsafe.

**Comment by julian99m** [comment]
Hi @tywalch, 
thanks for the clarification and for doing the research 😄 
I understand the technical limitation that is associated to my "desired" behavior, but I would still suggest that a more explicit description of the provided value (especially for the case of add/subtract/append/.... operations, in contrast to the set operation) should be added to the documentation.

Thanks! :)

**Comment by tywalch** [comment]
Absolutely! This is good feedback for the documentation, thank you!
