### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by kujtimiihoxha** [tywalch/electrodb#62]
The library is missing a license that permits use of it in other products.

The reason I am asking for this is that I would like to use this in a project and probably contribute to it (I am looking into additional update operations), but reading through the [GH docs](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository#choosing-the-right-license) I found this section

 **However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work**.
 
 Thanks for all the work you put into this library :)

**Comment by tywalch** [comment]
Updated, I had been meaning to do that 👍 

Let me know if you have an issues preventing you from doing what you need with the library, I appreciate the Issues you've made.

**Comment by kujtimiihoxha** [comment]
@tywalch thanks for the quick response, I do not see the update is it in a branch?

**Comment by tywalch** [comment]
@kujtimiihoxha How about now? I'll be sure to get this also out on NPM at the end of the day 👍

**Comment by kujtimiihoxha** [comment]
@tywalch thanks a lot :). I will see if I can wrap my head around the implementation and try to add `Add/Remove/Subtract` functionality for the update/patch methods 👍

**Comment by tywalch** [comment]
Regarding `Add/Remove/Subtract` I have local PR that I've been chipping away at to support a different syntax than the current `set` syntax. The code around `update` is unfortunately a bit coupled with specifically `set` operations so some of that work is decoupling those parts and build something that is a bit more extendable. Not to say a lot of it isn't salvageable, but it's a bit of a bigger job because of that.  

Is Add/Remove/Subtract functionality your hoping to use relatively soon? I have some other initiatives if you'd like to contribute quickly?

Regarding update/patch on the whole, I have local PR that I've been chipping away at to support a different syntax than the current `set` syntax. It would resemble the `where` syntax. One of the shortcomings of the object syntax for `set` is that when data structures like Map/List/Set are added they'll need better support. For example it would look something like this:

```
entity.update((attr, op) => [
    op.set(attr.prop1, "value"),
    op.add(attr.prop2, 10),
    op.append(attr.prop3.listOnMap("abc"), // note: dot syntax will work on attributes
    op.append(attr.prop3.setOnMap("def") // note: using append on both sets and lists 
]) 
```
